### ISSUE TITLE
uncertain detail about the position of pasting chatpdf api key。

### ISSUE THREAD

**Issue by secondbrain-note** [chrisgrieser/pdf-summarizer-alfred#1]
### Feature Requested

Excuse me, this is a good alfred workflow, could you please add a screenshot displaying the position where to paste chatapf api key. I am confused about that.
Thank you!

### Relevant Screenshot
<img width="899" alt="图片" src="https://github.com/chrisgrieser/pdf-summarizer-alfred/assets/69676588/01257674-508d-4d04-87ff-5a7f61a8d7f5">

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
It's the same as [with every Alfred workflow](https://www.alfredapp.com/help/workflows/user-configuration/).

![Pasted image 2023-10-22 at 13 17 51@2x](https://github.com/chrisgrieser/pdf-summarizer-alfred/assets/73286100/012734c6-116c-4014-aaa8-9be84401ff06)
![Pasted image 2023-10-22 at 13 18 49@2x](https://github.com/chrisgrieser/pdf-summarizer-alfred/assets/73286100/c9dcf1f8-0590-469f-9510-9e971f16fb2a)

**Comment by secondbrain-note** [comment]
Thank you for your reply!
