### ISSUE TITLE
 [Bug]: the app doesn't retrieve information from chatpdf

### ISSUE THREAD

**Issue by jhs1965net** [chrisgrieser/pdf-summarizer-alfred#2]
### Bug Description

I only retrieve :
[
  {
    \

### Relevant Screenshot

<img width="1202" alt="Screenshot 2024-01-10 at 13 05 07" src="https://github.com/chrisgrieser/pdf-summarizer-alfred/assets/113262694/c80880bd-5adf-447e-8e88-b29e3868d488">

### To Reproduce

toggle Alfred and by universal key or direct from finder the script begins  but just give me : 
[
  {
    \

in a text file

### Debugging Log

```Text
[13:10:50.633] Logging Started...
[13:12:17.515] PDF Summarizer[Hotkey] Processing complete
[13:12:17.524] PDF Summarizer[Hotkey] Passing output '(
    "/Users/jameshamilton/Downloads/Harper, K. N. - Armelagos, G. J. 2013, [87545],Genomics, the origins of agriculture, and our changin copy 2.pdf"
)' to Run Script
[13:12:18.113] STDERR: PDF Summarizer[Run Script] curl: (26) Failed to open/read local data from file/application
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1325  100  1042  100   283   2854    775 --:--:-- --:--:-- --:--:--  3630
[13:12:18.119] PDF Summarizer[Run Script] Processing complete
[13:12:18.120] PDF Summarizer[Run Script] Passing output '' to Large Type
[13:12:18.121] PDF Summarizer[Run Script] Passing output '' to Run Script
```

### Workflow Configuration
(removed due to API key leaking)

### Checklist

- [X] I have [updated to the latest version](./releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
There seems to be a problem with the PDF. Could you attach the PDF, so I can have a look?

**Comment by jhs1965net** [comment]
Here it is,
  but I have also the problem with another pdf
James

**Comment by chrisgrieser** [comment]
there is no attachment. Please do not use email to respond to github issues, since they are quite buggy.

**Comment by jhs1965net** [comment]
[Harper, K. N. - Armelagos, G. J. 2013, [87545],Genomics, the origins of agriculture, and our changin copy 2.pdf](https://github.com/chrisgrieser/pdf-summarizer-alfred/files/13888040/Harper.K.N.-.Armelagos.G.J.2013.87545.Genomics.the.origins.of.agriculture.and.our.changin.copy.2.pdf)

**Comment by jhs1965net** [comment]
[Varian, B. J., Weber, K. T. & Erdman, S. E. 2023, [121406],Oxytocin and the microbiomeComprehensive 5259.pdf](https://github.com/chrisgrieser/pdf-summarizer-alfred/files/13888049/Varian.B.J.Weber.K.T.Erdman.S.E.2023.121406.Oxytocin.and.the.microbiomeComprehensive.5259.pdf)

**Comment by chrisgrieser** [comment]
The issue is that your filenames include `,`. Commas are treated as enumeration, so ChatPDF thinks you are trying to upload multiple files, one `Varian`, another `B. J.`, another `Weber`, etc. And since those files do not exist, ChatPDF fails.

That's an issue on ChatPDF's side, and unfortunately there is nothing I can do about that on my end. Simply removing the commas from the filenames will fix the issue though.

By the way, there are actually many apps that have problems with commas (or other special characters) in filenames, so it is actually good practice to only have letters, digits, and the `-_.` characters in your filenames, since this also avoids annoying issues elsewhere.

**Comment by jhs1965net** [comment]
Chris I really appreciate your time and concern, I am writing a book about evolution, epigenetic and socialisation 
more than 3000 pdf in bookends and Zotero so I really enjoy using your app and read about all the knowledge you write down. I have also some publications about Adverse childhood experiences and I ran a little  team for research in those topics
kindly and thanks a lot.

Dr James Hamilton

**Comment by jhs1965net** [comment]
it worked !!!! 
is there any possibility to chat with the same pdf?

**Comment by chrisgrieser** [comment]
Unfortunately not, this workflow is only to get a quick-and-dirty summary.

To chat with the PDF, you can simply use the ChatPDF website?
